### PR TITLE
basically all the initial work is done

### PR DESCRIPTION
**Pull request by benneti**
i restore, backup, and upgrade definitely need some additional work.

But basic installation should work and I hope basic upgrades (and backups) work, too.

### CODE REVIEW

**Comment by centralscrutinizer21** [comment]
> i restore, backup, and upgrade definitely need some additional work.
> 
> But basic installation should work and I hope basic upgrades (and backups) work, too.

Hi Benneti i was trying to install this bridge on my yunohost server, but i think there is still no build for armv7? I am running yunohost on a raspberri pi4. Mautrix-whatsapp works fine for me i was hoping to get telegram and signal bridged as well. Tell me if I can help somehow

**Comment by benneti** [comment]
Hi, how did you try to install I and what is the exact error you get?
As this is a pure python bridge it is no surprise there is no specific build for armv7 (I am on armhf myself and it works) it just createss a venv and should build all dependencies local if something misses.

**Comment by centralscrutinizer21** [comment]
I have tried again to install from ssh here is the log:
https://paste.yunohost.org/raw/lozujuvupa

**Comment by benneti** [comment]
It might be that the version your pip installs (1.4.something) is to new for me it worked but it used 1.3.something

**Comment by centralscrutinizer21** [comment]
Ok thanks, I think I'll wait as well

**Comment by benneti** [comment]
OK, in this case you'll see it as soon as I push an update to my fork; also feel free to ping me if there is a new update and I miss it

**Comment by centralscrutinizer21** [comment]
Well I opened an account on github just to be able to contact you for this project, still learning and I have just started following you, I will add tulir project as well. Any idea about the mautrix-signal for yunohost? Is someone doing something?

**Comment by benneti** [comment]
I changed the version to rc1, so you can try installing again, I also changed some other things so let me know whether the installation works.

**Comment by centralscrutinizer21** [comment]
Installation was succesful! I am still testing all the functions but big thumbs up!

**Comment by benneti** [comment]
Great to hear!

**Comment by gautz** [comment]
congrats! do you want to be maintainer of this app? if yes you can ask for write access in the yunohost-apps matrix room. @tituspijean could you merge this PR in ``master`` branch and create a ``testing`` one plz?

**Comment by benneti** [comment]
I can maintain it for as long as I use it if this is fine.
(I plan to switch from yunohost to nixos on my homelab in the next year or so; so this will probably not be too long)

**Comment by Gredin67** [comment]
@benneti did you test the helper ``write_bridge_config``? is it a new Yunohost approach to customize config files? You don't need to copy the template file first? How does it know where to find the config file? Are'nt you missing some parameters?

I did not manage to install on x86
https://paste.yunohost.org/raw/irayoxerol

**Comment by benneti** [comment]
I did not test on x86(_amd64) only on arm.
The write_bridge_config function is defined in common, because I wanted to use this in upgrade and not duplicate any code (incase defaults change and so on).
I do not need to copy the template and do the substitutions manually as you can see in the function this is handled by the ynh_add_config function.

Did you try whether the installation steps (from mautrix_telegram work manually) as it seems this fails in the pip command and might be an upstream problem.

**Pull request merged**
