### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Add libffi-dev dependency

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Gredin67** [comment]
what about upgrading to 0.11.0 before merging?
Note following (https://github.com/mautrix/telegram/releases):
The automatic database migration requires you to be on the latest legacy database version. If you were running any v0.10.x version, you should be on the latest version already. Otherwise, update to v0.10.2 first, upgrade the database with alembic, then upgrade to v0.11.0 (or higher).

So we should pre-upgrade to 0.10.2 before upgrading to 0.11.0 or at least notice the users.

**Comment by benneti** [comment]
I think upgrading to 0.11 is a great Idea, additionally I believe from 0.11 on alembic is not necessary anymore and no versions prior to 0.10.x where ever published to this more official repo. So a notification probably is enough and during the upgrade the alembic stuff can probably be removed.

**Comment by Gredin67** [comment]
just tried an upgrade on a test server:
https://paste.yunohost.org/raw/ujunigacav

Before the upgrade the service was failing https://paste.yunohost.org/ehuqajixor

**Comment by Gredin67** [comment]
`conf/config.yaml` may need to be upgraded, see https://github.com/mautrix/telegram/compare/v0.10.1...v0.10.2

**Comment by Gredin67** [comment]
and maybe something 
https://github.com/YunoHost-Apps/mautrix_telegram_ynh/blob/testing/scripts/_common.sh#L15-L26
https://github.com/YunoHost-Apps/mautrix_telegram_ynh/blob/testing/scripts/install#L178-L181

**Comment by ericgaspar** [comment]
!testme

**Comment by Gredin67** [comment]
there is still an issue with the config file,
```
rning: Traceback (most recent call last):
Warning:   File "/usr/lib/python3.9/logging/config.py", line 564, in configure
Warning:     handler = self.configure_handler(handlers[name])
Warning:   File "/usr/lib/python3.9/logging/config.py", line 745, in configure_handler
Warning:     result = factory(**kwargs)
Warning:   File "/usr/lib/python3.9/logging/handlers.py", line 153, in __init__
Warning:     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
Warning:   File "/usr/lib/python3.9/logging/handlers.py", line 58, in __init__
Warning:     logging.FileHandler.__init__(self, filename, mode=mode,
Warning:   File "/usr/lib/python3.9/logging/__init__.py", line 1142, in __init__
Warning:     StreamHandler.__init__(self, self._open())
Warning:   File "/usr/lib/python3.9/logging/__init__.py", line 1171, in _open
Warning:     return open(self.baseFilename, self.mode, encoding=self.encoding,
Warning: IsADirectoryError: [Errno 21] Is a directory: '/var/log/mautrix_telegram/mautrix_telegram.log'
```

We should just get rid of these
https://github.com/YunoHost-Apps/mautrix_telegram_ynh/blob/testing/scripts/_common.sh#L15-L26
https://github.com/YunoHost-Apps/mautrix_telegram_ynh/blob/testing/scripts/install#L178-L181
use the helper as here instead https://github.com/YunoHost-Apps/mautrix_signal_ynh/blob/master/scripts/install#L150

**Comment by yalh76** [comment]
!testme

**Pull request merged**
