### PR TITLE
try to fix CI

### PR DESCRIPTION
**Pull request by benneti**
## Problem
- try to make CI work
- The real problem is I have no idea why it fails
## Solution
- trial and error...

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/REPLACEBYYOURAPP_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by benneti** [comment]
@ericgaspar I do not know why you closed the previous one, so here a new one...
(If me rewriting the history caused problems I am sorry for that, but as this might gain some tracktion I prefer it if my commits are from the email address I use with github)
Maybe @Gredin67 could help with the CI problems

**Comment by benneti** [comment]
I think I finally figured out the problem, mautrix_telegram fails to generate the synapse config when I use the values from the example configuration...

**Comment by benneti** [comment]
locally all tests (apart from port already in use pass)

**Comment by benneti** [comment]
!testme

**Comment by benneti** [comment]
Screenshot from 2021-09-10 16-57-29

**Comment by ericgaspar** [comment]
!testme

**Comment by benneti** [comment]
thanks! Tests show all green https://ci-apps-dev.yunohost.org/ci/job/3109 merging this into master as it improves the quality a bit. 

There is some stuff left like rewriting the readme via the manifest automation but I do not have time for that right now

**Pull request merged**
