### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Solution
- *[Apply last example_ynh](https://github.com/YunoHost-Apps/mautrix_telegram_ynh/commit/9b93bd2e2cdf9a32ac52b579abbff486e4b1eb1d)*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/mautrix_telegram_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by benneti** [comment]
Hey, I don't use yunohost anymore so I cannot test whether this actually works (apart from building) and don't feel comfortable merging it.
As I already said a few times it would be great if someone using yunohost and the bridge could take over.

(sorry for the inconvenience)

**Comment by yalh76** [comment]
Thanks,
Well, as there is no fundamental changes, I'll move forward

**Pull request merged**
