### PR TITLE
upgrade to 0.10.1 and accomodate upstream repo rename

### PR DESCRIPTION
**Pull request by benneti**
would really like to check this with CI but I have no idea how..
# PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/REPLACEBYYOURAPP_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by benneti** [comment]
upgrade fails due to underdetermined sed command...

**Comment by benneti** [comment]
everything should work now

**Comment by Gredin67** [comment]
!testme

**Comment by benneti** [comment]
Ah cool, what exactly do the tests test?

**Comment by Gredin67** [comment]
you should add following file: https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/blob/master/check_process
Then write !testme in the PR message stream
The test checks for install, backup, restore, upgrade and remove.
If it works properly we can ask to add the app in the yunohost app list

**Comment by Gredin67** [comment]
see here https://github.com/YunoHost/apps/pull/1221

**Comment by Gredin67** [comment]
btw what about setting you the maintainer here: 
manifest.json 
As I am not a telegram user I am not able to test and maintain it properly...

**Comment by benneti** [comment]
!testme

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
obviously only people member of the yunohost-apps group can run the CI. You can ask for it in the chat.

**Comment by benneti** [comment]
superseded by https://github.com/YunoHost-Apps/mautrix_telegram_ynh/pull/5

**Pull request closed without merging**
