### PR TITLE
Config panel

### PR DESCRIPTION
**Pull request by thardev**
## Notes
- [x] Finish install script
- [x] Finish upgrade script
     - [x] Test permissions after upgrade is applied (if they are correctly restored) 
- [x] Test config panel
     - [x] Test addition/removal of roles
     - [x] Test boolean fields
- [x] Test setters/getters

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
Guess you're missing this : 
* https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/blob/master/scripts/install#L100-L103
* https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/blob/master/scripts/upgrade#L84-L244
And maybe other funny things, can you double-check ?

**Comment by thardev** [comment]
Yes, some stuff need to be finished but I'm not able to work on it right now. As soon as I have time again to finish it, I'll take care of it 🙂 👍

**Comment by thardev** [comment]
!testme

**Pull request merged**
