### PR TITLE
Packaging v2

### PR DESCRIPTION
**Pull request by thardev**
## TODO

- [x] Refactor install script
- [x] Test install script
- [x] Refactor backup script
- [x] Test backup script
- [x] Refactor remove script
- [x] Test remove script
- [x] Refactor upgrade script
- [x] Test upgrade script
- [x] Refactor restore script
- [x] Test restore script
- [x] Add manifest TOML
- [x] Refactor Systemd service
- [x] Test Systemd service
- [x] Add tests and remove check_process
- [x] Use new docs structure
- [x] Refactor `updater.sh` script

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
!testme

**Comment by Gredin67** [comment]
!testme

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
@Gredin67 Thank you for your help here, I've managed to solve the restore issue but could you maybe check what could be the reason why the upgrade from `v0.12.0` fails?
I've tested on my dev box and it works as expected, might be related to the Yunorunner distro version?
Thank you 🙂 

My dev box:

RaspberryPi 3
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
@Gredin67 no more help needed, I've figured it out in the forum and myself. I'll merge this now 🙂

**Pull request merged**
