### PR TITLE
Configure end-to-bridge encryption

### LINKED ISSUE #15: e2be is not configured, like AT ALL
**Problem:** Even though the end to bridge option is enabled, the bridge is not configured correctly. 

You can **reproduce** it by installing the bridge, using the the e2be option and checking the config.yaml. The bot will not work neither and error out with "This bridge is not configured to use encryption"

**Desired goals**
1. install/remove the optional dependencies
2. enable at least the config option to allow encrypted chats. If that works reliably, the “force encryption“ option should be enabled. 

**Changes** that could resolve it:
- add a variable in the config, like it is done with `__SERVER_NAME__` to corrispond to the switch
- install python-olm, pycryptodome and unpaddedbase64

but im not an expert, its more of an educated guess from the mautrx docs and looking at the config scripts. A low effort, imho shitty workaround would be to remove the e2be switch.

**Environment:** VPS with Debian 10 running YH 4.3.5 (stable).

This is the same with other mautrix bridges. See https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/issues/40 and https://github.com/YunoHost-Apps/mautrix_signal_ynh/issues/35

### PR DESCRIPTION
**Pull request by thardev**
## Problem
- End-to-bridge is not configured on install when selecting yes to configure it
- Fix #15 

## Solution
- Add steps on install and upgrade script to configure it.

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Additional info
- ~~Tested manually on Debian Buster on a Raspi.~~

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/mautrix_telegram_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by thardev** [comment]
!testme

**Comment by benneti** [comment]
Hey, I don't use yunohost anymore so I cannot test whether this actually works (apart from building) and don't feel comfortable merging it.
As I already said a few times it would be great if someone using yunohost and the bridge could take over.

(sorry for the inconvenience)

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
!testme

**Pull request merged**
